import type { Metadata } from "next";
import { Inter, Noto_Sans_Thai_Looped } from "next/font/google";
import "@scss/global.scss";
import { SupabaseProvider } from "@/components/supabase-provider";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-inter",
});

const notoSansThaiLooped = Noto_Sans_Thai_Looped({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext", "thai"],
  variable: "--font-noto-sans-thai-looped",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${notoSansThaiLooped.variable}`}>
        <SupabaseProvider>{children}</SupabaseProvider>
      </body>
    </html>
  );
}
